# Generated by Django 5.2.13 on 2026-04-27 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0013_remove_medicamento_historial_ventas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('VENTA', 'Venta'), ('AJUSTE', 'Ajuste'), ('INGRESO', 'Ingreso'), ('DEVOLUCION', 'Devolución')], db_index=True, max_length=20)),
                ('cantidad', models.IntegerField()),
                ('stock_anterior', models.PositiveIntegerField()),
                ('stock_posterior', models.PositiveIntegerField()),
                ('motivo', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Historial de Stock',
                'verbose_name_plural': 'Historiales de Stock',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medicamentos', to='farmacia.proveedor'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='sku',
            field=models.CharField(db_index=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='stock',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='venta',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddIndex(
            model_name='medicamento',
            index=models.Index(fields=['sku'], name='farmacia_me_sku_812618_idx'),
        ),
        migrations.AddIndex(
            model_name='medicamento',
            index=models.Index(fields=['stock'], name='farmacia_me_stock_b1edad_idx'),
        ),
        migrations.AddIndex(
            model_name='medicamento',
            index=models.Index(fields=['proveedor', 'stock'], name='farmacia_me_proveed_ab2ac7_idx'),
        ),
        migrations.AddIndex(
            model_name='medicamento',
            index=models.Index(fields=['fecha_vencimiento'], name='farmacia_me_fecha_v_987155_idx'),
        ),
        migrations.AddField(
            model_name='historialstock',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_stock', to='farmacia.medicamento'),
        ),
        migrations.AddField(
            model_name='historialstock',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_stock', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historialstock',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial', to='farmacia.venta'),
        ),
        migrations.AddIndex(
            model_name='historialstock',
            index=models.Index(fields=['medicamento', 'fecha_creacion'], name='farmacia_hi_medicam_c02cf3_idx'),
        ),
        migrations.AddIndex(
            model_name='historialstock',
            index=models.Index(fields=['usuario', 'fecha_creacion'], name='farmacia_hi_usuario_a306e6_idx'),
        ),
        migrations.AddIndex(
            model_name='historialstock',
            index=models.Index(fields=['tipo', 'fecha_creacion'], name='farmacia_hi_tipo_febba2_idx'),
        ),
    ]
