# Generated by Django 5.2.13 on 2026-04-27 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0014_historialstock_alter_medicamento_precio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_dni', models.CharField(help_text='Ej: 12.345.678-9 o 12345678', max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('alergias', models.TextField(blank=True, help_text='Ej: Penicilina, Aspirina')),
                ('medicamentos_contraindicados', models.TextField(blank=True, help_text='Medicamentos que no puede comprar')),
                ('cliente_vip', models.BooleanField(default=False)),
                ('descuento_vip', models.DecimalField(decimal_places=2, default=0, help_text='Descuento en % para cliente VIP', max_digits=5)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['rut_dni'], name='farmacia_cl_rut_dni_77c3b6_idx'), models.Index(fields=['email'], name='farmacia_cl_email_27a87e_idx')],
            },
        ),
        migrations.AddField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, help_text='Cliente que realizó la compra (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venta_set', to='farmacia.cliente'),
        ),
        migrations.CreateModel(
            name='LoteMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField(db_index=True)),
                ('cantidad_ingresada', models.PositiveIntegerField()),
                ('cantidad_disponible', models.PositiveIntegerField()),
                ('precio_costo', models.DecimalField(decimal_places=2, help_text='Precio de costo de este lote', max_digits=10)),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='farmacia.medicamento')),
                ('proveedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmacia.proveedor')),
            ],
            options={
                'verbose_name': 'Lote de Medicamento',
                'verbose_name_plural': 'Lotes de Medicamentos',
                'ordering': ['fecha_vencimiento'],
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo', models.CharField(choices=[('vencido', 'Medicamento Vencido'), ('defecto', 'Defecto/Dañado'), ('no_venta', 'Cambio de Opinión'), ('error_venta', 'Error de Vendedor'), ('otro', 'Otro Motivo')], max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('registrada', 'Registrada'), ('aprobada', 'Aprobada'), ('devuelta_proveedor', 'Devuelta a Proveedor'), ('acreedor_cliente', 'Acreedor al Cliente')], default='registrada', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.medicamento')),
                ('usuario_aprueba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_registra', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_registradas', to=settings.AUTH_USER_MODEL)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='farmacia.venta')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farmacia.lotemedicamento')),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.AddIndex(
            model_name='lotemedicamento',
            index=models.Index(fields=['medicamento', 'fecha_vencimiento'], name='farmacia_lo_medicam_cdbd85_idx'),
        ),
        migrations.AddIndex(
            model_name='lotemedicamento',
            index=models.Index(fields=['fecha_vencimiento'], name='farmacia_lo_fecha_v_9c542c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lotemedicamento',
            unique_together={('medicamento', 'numero_lote')},
        ),
        migrations.AddIndex(
            model_name='devolucion',
            index=models.Index(fields=['venta'], name='farmacia_de_venta_i_b87727_idx'),
        ),
        migrations.AddIndex(
            model_name='devolucion',
            index=models.Index(fields=['estado'], name='farmacia_de_estado_3b396d_idx'),
        ),
    ]
