# Generated by Django 5.2.13 on 2026-04-27 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0015_cliente_venta_cliente_lotemedicamento_devolucion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='lote',
            field=models.ForeignKey(blank=True, help_text='Lote medicamento (para FIFO)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='farmacia.lotemedicamento'),
        ),
    ]
