# Generated by Django 5.2.13 on 2026-04-27 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0016_venta_lote'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_boleta', models.CharField(db_index=True, help_text='Formato: BV-2026-00001', max_length=15, unique=True)),
                ('folio', models.PositiveIntegerField(db_index=True, help_text='Número secuencial (1, 2, 3...)', unique=True)),
                ('rut_farmacia', models.CharField(max_length=20)),
                ('nombre_farmacia', models.CharField(default='FARMACIA COLLICO', max_length=255)),
                ('direccion_farmacia', models.CharField(max_length=255)),
                ('telefono_farmacia', models.CharField(blank=True, max_length=20)),
                ('cliente_rut', models.CharField(blank=True, max_length=20, null=True)),
                ('cliente_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('base_imponible', models.DecimalField(decimal_places=2, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', '💵 Efectivo'), ('DEBITO', '🏧 Débito'), ('CREDITO', '💳 Crédito'), ('TRANSFERENCIA', '🏦 Transferencia')], max_length=20)),
                ('referencia_pago', models.CharField(blank=True, help_text='Ref. transacción, últimos 4 dígitos, etc', max_length=100, null=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='boletas/%Y/%m/')),
                ('estado', models.CharField(choices=[('EMITIDA', 'Emitida'), ('ANULADA', 'Anulada'), ('IMPRESA', 'Impresa')], db_index=True, default='EMITIDA', max_length=20)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Boleta',
                'verbose_name_plural': 'Boletas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='CarritoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Item Carrito',
                'verbose_name_plural': 'Items Carrito',
            },
        ),
        migrations.CreateModel(
            name='CarritoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('EN_CONSTRUCCION', 'En construcción'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], db_index=True, default='EN_CONSTRUCCION', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento aplicado', max_digits=5)),
                ('base_imponible', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('fecha_completacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Carrito de Venta',
                'verbose_name_plural': 'Carritos de Venta',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota', models.CharField(db_index=True, help_text='Formato: NC-2026-00001', max_length=15, unique=True)),
                ('folio', models.PositiveIntegerField(db_index=True, help_text='Número secuencial', unique=True)),
                ('motivo', models.CharField(choices=[('ANULACION', 'Anulación de venta'), ('DEVOLUCION', 'Devolución de medicamento'), ('DESCUENTO', 'Descuento especial'), ('AJUSTE', 'Ajuste de precio')], max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Detalles del motivo')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto a acreditar', max_digits=12)),
                ('requiere_aprobacion', models.BooleanField(default=False, help_text='¿Necesita aprobación supervisor?')),
                ('aprobada', models.BooleanField(db_index=True, default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('TRANSFERENCIA', 'Transferencia')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cambio', models.DecimalField(decimal_places=2, default=0, help_text='Solo para efectivo', max_digits=12)),
                ('referencia', models.CharField(blank=True, help_text='Ref. débito, número cheque, etc', max_length=100, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterModelOptions(
            name='venta',
            options={'ordering': ['-fecha']},
        ),
        migrations.AddField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('COMPLETADA', 'Completada'), ('ANULADA', 'Anulada'), ('DEVUELTA', 'Devuelta')], db_index=True, default='COMPLETADA', max_length=20),
        ),
        migrations.AddField(
            model_name='venta',
            name='numero_venta',
            field=models.CharField(blank=True, db_index=True, help_text='Número único de venta (VT-2026-00001)', max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['numero_venta'], name='farmacia_ve_numero__d490a7_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['vendedor', 'fecha'], name='farmacia_ve_vendedo_0c86f7_idx'),
        ),
        migrations.AddIndex(
            model_name='venta',
            index=models.Index(fields=['estado'], name='farmacia_ve_estado_35432d_idx'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='medicamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmacia.medicamento'),
        ),
        migrations.AddField(
            model_name='carritoventa',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carritos', to='farmacia.cliente'),
        ),
        migrations.AddField(
            model_name='carritoventa',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos_venta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='carrito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='farmacia.carritoventa'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='carrito',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boleta', to='farmacia.carritoventa'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='boleta_original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_credito', to='farmacia.boleta'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='usuario_aprueba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_credito_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='usuario_registra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_credito_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pago',
            name='boleta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='farmacia.boleta'),
        ),
        migrations.AddField(
            model_name='pago',
            name='carrito',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='farmacia.carritoventa'),
        ),
        migrations.AddIndex(
            model_name='carritoventa',
            index=models.Index(fields=['vendedor', 'estado'], name='farmacia_ca_vendedo_1ce073_idx'),
        ),
        migrations.AddIndex(
            model_name='carritoventa',
            index=models.Index(fields=['estado', 'fecha_creacion'], name='farmacia_ca_estado_4d266c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='carritoitem',
            unique_together={('carrito', 'medicamento')},
        ),
        migrations.AddIndex(
            model_name='boleta',
            index=models.Index(fields=['numero_boleta'], name='farmacia_bo_numero__b869f7_idx'),
        ),
        migrations.AddIndex(
            model_name='boleta',
            index=models.Index(fields=['folio'], name='farmacia_bo_folio_afceaf_idx'),
        ),
        migrations.AddIndex(
            model_name='boleta',
            index=models.Index(fields=['vendedor', 'fecha_emision'], name='farmacia_bo_vendedo_a4683d_idx'),
        ),
        migrations.AddIndex(
            model_name='boleta',
            index=models.Index(fields=['estado'], name='farmacia_bo_estado_ad3ee6_idx'),
        ),
        migrations.AddIndex(
            model_name='notacredito',
            index=models.Index(fields=['numero_nota'], name='farmacia_no_numero__235188_idx'),
        ),
        migrations.AddIndex(
            model_name='notacredito',
            index=models.Index(fields=['aprobada'], name='farmacia_no_aprobad_04d7b4_idx'),
        ),
        migrations.AddIndex(
            model_name='notacredito',
            index=models.Index(fields=['usuario_registra'], name='farmacia_no_usuario_bb2fd7_idx'),
        ),
    ]
