# Generated by Django 5.2.13 on 2026-04-27 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0017_boleta_carritoitem_carritoventa_notacredito_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='boleta',
            field=models.ForeignKey(blank=True, help_text='Boleta asociada a esta venta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='farmacia.boleta'),
        ),
    ]
