# Generated by Django 5.2.13 on 2026-04-28 02:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0018_venta_boleta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('ELIMINAR', 'Eliminar'), ('VER', 'Ver'), ('EXPORTAR', 'Exportar'), ('INTENTOFALLIDO', 'Intento fallido de acceso'), ('ACCESODENEGADO', 'Acceso denegado')], max_length=20)),
                ('objeto', models.CharField(max_length=50)),
                ('objeto_id', models.IntegerField()),
                ('detalles', models.TextField()),
                ('resultado', models.BooleanField(default=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Auditoría Log',
                'verbose_name_plural': 'Auditorías Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['usuario', 'timestamp'], name='farmacia_au_usuario_cf9f3b_idx'), models.Index(fields=['accion', 'timestamp'], name='farmacia_au_accion_ad861c_idx'), models.Index(fields=['objeto', 'objeto_id'], name='farmacia_au_objeto_717653_idx')],
            },
        ),
        migrations.CreateModel(
            name='RolPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador / Dueño'), ('VENDEDOR', 'Vendedor'), ('GERENTE', 'Gerente de Tienda'), ('CONTADOR', 'Contador')], default='VENDEDOR', max_length=20)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('estado_activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rol_permiso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol y Permiso',
                'verbose_name_plural': 'Roles y Permisos',
                'indexes': [models.Index(fields=['rol'], name='farmacia_ro_rol_a4f89e_idx'), models.Index(fields=['estado_activo'], name='farmacia_ro_estado__d5125b_idx')],
            },
        ),
    ]
