# Generated by Django 5.2.13 on 2026-05-02 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmacia', '0019_auditorialog_rolpermiso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='medicamento',
            name='tipo_venta',
            field=models.CharField(choices=[('libre', 'Venta libre (sin receta)'), ('receta_simple', 'Receta simple'), ('receta_retenida', 'Receta retenida (se queda en farmacia)'), ('controlado', 'Medicamento controlado (estupefaciente/psicotrópico)')], db_index=True, default='libre', help_text='Clasificación regulatoria del medicamento', max_length=20),
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('simple', 'Receta simple'), ('retenida', 'Receta retenida'), ('controlada', 'Receta de medicamento controlado')], db_index=True, max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de verificación'), ('verificada', 'Verificada'), ('rechazada', 'Rechazada')], db_index=True, default='pendiente', max_length=20)),
                ('nombre_medico', models.CharField(max_length=255)),
                ('rut_medico', models.CharField(blank=True, max_length=20)),
                ('especialidad', models.CharField(blank=True, max_length=100)),
                ('codigo_prestador', models.CharField(blank=True, help_text='Código/RUN ISP del médico tratante', max_length=50)),
                ('nombre_paciente', models.CharField(max_length=255)),
                ('rut_paciente', models.CharField(max_length=20)),
                ('numero_receta', models.CharField(blank=True, max_length=50)),
                ('fecha_emision', models.DateField(help_text='Fecha en que fue emitida la receta')),
                ('fecha_vencimiento_receta', models.DateField(blank=True, help_text='Fecha máxima para usar la receta (por defecto 30 días)', null=True)),
                ('archivo_receta', models.FileField(blank=True, help_text='Imagen o PDF de la receta (obligatorio para controlados)', null=True, upload_to='recetas/%Y/%m/')),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('carrito', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receta', to='farmacia.carritoventa')),
                ('registrada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas_registradas', to=settings.AUTH_USER_MODEL)),
                ('venta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receta', to='farmacia.venta')),
                ('verificada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas_verificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Receta Médica',
                'verbose_name_plural': 'Recetas Médicas',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(choices=[('receta_registrada', 'Receta registrada'), ('receta_verificada', 'Receta verificada'), ('receta_rechazada', 'Receta rechazada'), ('venta_bloqueada', 'Venta bloqueada por falta de receta'), ('venta_con_receta', 'Venta realizada con receta'), ('receta_retenida', 'Receta física retenida en farmacia')], db_index=True, max_length=30)),
                ('detalle', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('medicamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_recetas', to='farmacia.medicamento')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria_recetas', to=settings.AUTH_USER_MODEL)),
                ('receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditoria', to='farmacia.receta')),
            ],
            options={
                'verbose_name': 'Auditoría de Receta',
                'verbose_name_plural': 'Auditorías de Recetas',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='receta',
            field=models.ForeignKey(blank=True, help_text='Receta que autoriza la venta de este medicamento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_carrito', to='farmacia.receta'),
        ),
        migrations.AddField(
            model_name='venta',
            name='receta_venta',
            field=models.ForeignKey(blank=True, help_text='Receta médica que autorizó esta venta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_autorizadas', to='farmacia.receta'),
        ),
        migrations.AddIndex(
            model_name='receta',
            index=models.Index(fields=['tipo', 'estado'], name='farmacia_re_tipo_f97362_idx'),
        ),
        migrations.AddIndex(
            model_name='receta',
            index=models.Index(fields=['rut_paciente'], name='farmacia_re_rut_pac_1854a1_idx'),
        ),
        migrations.AddIndex(
            model_name='receta',
            index=models.Index(fields=['fecha_emision'], name='farmacia_re_fecha_e_714830_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriareceta',
            index=models.Index(fields=['evento', 'timestamp'], name='farmacia_au_evento_d261d1_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriareceta',
            index=models.Index(fields=['medicamento', 'timestamp'], name='farmacia_au_medicam_0370dd_idx'),
        ),
        migrations.AddIndex(
            model_name='auditoriareceta',
            index=models.Index(fields=['usuario', 'timestamp'], name='farmacia_au_usuario_391660_idx'),
        ),
    ]
